import { NextResponse } from 'next/server';
import { createIssueComment } from '@/lib/github';

export async function POST(req: Request) {
  try {
    const { owner, repo, issueNumber, fix, githubToken } = await req.json();

    if (!owner || !repo || !issueNumber || !fix) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const commentBody = `### Proposed fix generated by BugWhisperer 🐛

Here is the suggested fix for this issue:

\`\`\`typescript
${fix}
\`\`\`
`;

    const result = await createIssueComment(owner, repo, issueNumber, commentBody, githubToken);

    return NextResponse.json({ success: true, url: result.html_url });
  } catch (error: any) {
    console.error('Apply API Error:', error);
    return NextResponse.json({ error: error.message || 'An error occurred while posting the comment' }, { status: 500 });
  }
}
